version: '3.8'

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=https://your-domain.com/api
      - REACT_APP_JITSI_DOMAIN=${JITSI_DOMAIN}

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  jitsi-web:
    image: jitsi/web:stable-7882
    restart: unless-stopped
    volumes:
      - ./docker/jitsi/web:/config:Z
    environment:
      - ENABLE_AUTH=1
      - AUTH_TYPE=jwt
      - PUBLIC_URL=https://${JITSI_DOMAIN}
      - XMPP_DOMAIN=${JITSI_XMPP_DOMAIN}
      - JWT_APP_ID=${JITSI_APP_ID}
      - JWT_APP_SECRET=${JITSI_APP_SECRET}

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/ssl:/etc/nginx/ssl
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
      - jitsi-web

volumes:
  mysql_data: 